# Generated by Django 3.2.7 on 2021-09-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_payment_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
